name: NuGet Package Publish

on:
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
    
    - name: Pack
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /t:NetLibDirectshowCapture:pack /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Publish
      working-directory: NetLibDirectshowCapture/NetLibDirectshowCapture/bin/Release
      run: nuget push "$(Get-ChildItem -Filter "*.nupkg")" ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json
